// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpHXOzcFIRZsqJ7k-nmcbkW7pAX_KJGkg',
    appId: '1:918148891023:web:1193a0b262e3028fa28bfa',
    messagingSenderId: '918148891023',
    projectId: 'sample-project-a80be',
    authDomain: 'sample-project-a80be.firebaseapp.com',
    storageBucket: 'sample-project-a80be.appspot.com',
    measurementId: 'G-PCW3W22J1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1MggCA6jIflEalKB8ziBaCvajzm4u1-4',
    appId: '1:918148891023:android:ba0237cfd359d6b4a28bfa',
    messagingSenderId: '918148891023',
    projectId: 'sample-project-a80be',
    storageBucket: 'sample-project-a80be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeN-ydywEYdLb1bqngt1OaPwC6YzU0KAU',
    appId: '1:918148891023:ios:7ba7e435aa342205a28bfa',
    messagingSenderId: '918148891023',
    projectId: 'sample-project-a80be',
    storageBucket: 'sample-project-a80be.appspot.com',
    androidClientId: '918148891023-9tebgju5fo7pqd9qv0j0rb8pv8mb5233.apps.googleusercontent.com',
    iosClientId: '918148891023-f179niavfgol707k0bbe4puj0uqj3h28.apps.googleusercontent.com',
    iosBundleId: 'com.photohub.photoHub',
  );
}
